'use client';

import { SyntheticEvent, useCallback, useEffect, useState } from 'react';
import { ArrowDown, Check, ChefHat, ChevronRight, Clock3, Flame, Globe2, Lightbulb, MessageSquarePlus, Plus, Search, Send, Star, Utensils, X, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';

type Lang = 'zh' | 'en';
type Recipe = {
  id: string; zh: string; en: string; difficulty: number; minutes: number; power: string;
  ingredients: string[]; ingredientEn: string[]; descZh: string; descEn: string;
  stepsZh: string[]; stepsEn: string[]; tested?: boolean;
};
type WebMcpContext = { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> };
declare global { interface Document { modelContext?: WebMcpContext } }

const recipes: Recipe[] = [
  { id:'tomato-egg', zh:'西红柿炒鸡蛋', en:'Tomato & Egg Stir-fry', difficulty:1, minutes:12, power:'1400W → 800W', tested:true, ingredients:['西红柿','鸡蛋','小葱'], ingredientEn:['tomato','egg','scallion'], descZh:'留学生厨房的第一道中式快炒。用功率而不是“中大火”来控制结果。', descEn:'A first Chinese stir-fry for any student kitchen—guided by watts, not vague heat levels.', stepsZh:['1400W 热锅 40 秒，倒油后下蛋液。','蛋液刚凝固就盛出，避免余温变老。','西红柿 1200W 炒出汁，转 800W 回锅合炒。'], stepsEn:['Preheat at 1400W for 40 seconds; add oil and beaten eggs.','Remove eggs as soon as softly set to avoid overcooking.','Cook tomatoes at 1200W until juicy; return eggs at 800W.'] },
  { id:'pepper-mince', zh:'辣椒炒肉末', en:'Pepper with Minced Pork', difficulty:2, minutes:16, power:'1600W → 1000W', tested:true, ingredients:['辣椒','猪肉末','蒜'], ingredientEn:['pepper','minced pork','garlic'], descZh:'肉末炒散后再放辣椒，适合单灶电磁炉的顺序烹饪。', descEn:'Brown the mince first, then add peppers—ideal sequencing for a single induction hob.', stepsZh:['锅烧到 1600W，肉末分散下锅。','肉末变色后推到一侧，蒜末爆香。','加入辣椒，1000W 翻炒至断生。'], stepsEn:['Heat to 1600W and spread the mince across the pan.','When browned, push aside and bloom the garlic.','Add peppers; finish at 1000W until just tender.'] },
  { id:'pepper-pork', zh:'辣椒炒肉片', en:'Pepper Pork Stir-fry', difficulty:2, minutes:20, power:'1600W → 900W', tested:true, ingredients:['辣椒','猪肉片','姜'], ingredientEn:['pepper','sliced pork','ginger'], descZh:'薄切和提前腌制是关键，高功率快炒避免肉片出水。', descEn:'Thin slicing and a short marinade keep the pork tender during high-power cooking.', stepsZh:['肉片提前用生抽和淀粉腌 10 分钟。','1600W 快速滑炒至八成熟，先盛出。','辣椒炒香后转 900W，肉片回锅。'], stepsEn:['Marinate pork with soy sauce and starch for 10 minutes.','Stir-fry at 1600W until almost done; remove.','Cook peppers, lower to 900W, then return pork.'] },
  { id:'cucumber-mince', zh:'黄瓜炒肉末', en:'Cucumber with Minced Pork', difficulty:2, minutes:15, power:'1400W → 900W', tested:true, ingredients:['黄瓜','猪肉末','蒜'], ingredientEn:['cucumber','minced pork','garlic'], descZh:'黄瓜最后下锅，保留脆度，也减少电磁炉锅内积水。', descEn:'Add cucumber last to preserve crunch and prevent liquid pooling on induction.', stepsZh:['1400W 将肉末炒至微焦。','加入蒜末和调味料快速翻匀。','下黄瓜，900W 炒 60–90 秒即出锅。'], stepsEn:['Brown mince at 1400W until lightly crisp.','Add garlic and seasonings; toss quickly.','Add cucumber at 900W for just 60–90 seconds.'] },
  { id:'bok-choy', zh:'清炒小白菜', en:'Garlic Bok Choy', difficulty:1, minutes:8, power:'1600W', tested:true, ingredients:['小白菜','蒜'], ingredientEn:['bok choy','garlic'], descZh:'最短的入门菜：擦干菜叶、大功率、短时间。', descEn:'The shortest beginner recipe: dry leaves, high power, very little time.', stepsZh:['小白菜洗净后充分沥干。','1600W 热锅，下油和蒜末 10 秒。','先下菜梗再下菜叶，炒至刚变软。'], stepsEn:['Wash and thoroughly dry the bok choy.','At 1600W, add oil and garlic for 10 seconds.','Cook stems first, then leaves; stop as they soften.'] },
  { id:'bok-choy-mince', zh:'小白菜炒肉末', en:'Bok Choy with Minced Pork', difficulty:2, minutes:14, power:'1500W → 1000W', tested:true, ingredients:['小白菜','猪肉末','蒜'], ingredientEn:['bok choy','minced pork','garlic'], descZh:'一锅完成蛋白质和蔬菜，先荤后素避免白菜过熟。', descEn:'Protein and greens in one pan; cook meat first so the bok choy stays bright.', stepsZh:['1500W 炒散肉末并盛出多余油脂。','加入蒜末，再下小白菜梗。','转 1000W，下菜叶和肉末快速合炒。'], stepsEn:['Brown mince at 1500W and remove excess fat.','Add garlic, followed by bok choy stems.','Lower to 1000W; toss leaves and mince together.'] },
  { id:'fried-egg', zh:'煎荷包蛋', en:'Induction Fried Egg', difficulty:1, minutes:6, power:'1000W → 500W', tested:true, ingredients:['鸡蛋'], ingredientEn:['egg'], descZh:'先中功率定型，再低功率焖熟，解决电磁炉局部过热。', descEn:'Set at medium power, then finish low to handle induction hot spots.', stepsZh:['1000W 预热平底锅 30 秒并加油。','打入鸡蛋，边缘定型后转 500W。','加一勺水并盖盖，焖到蛋白完全凝固。'], stepsEn:['Preheat at 1000W for 30 seconds and add oil.','Crack in the egg; lower to 500W once edges set.','Add a spoonful of water, cover, and steam until white is set.'] },
];

const copy = {
  zh: { brand:'食知', sub:'留学生电磁炉菜谱', tested:'实测成功', guest:'访客投稿', myIngredients:'我现在有', ingredientHint:'先选择食材，我们会显示每道菜还缺什么', add:'输入食材后回车', recommend:'你现在最适合做', recommendSub:'按已有食材匹配，实测菜谱优先', can:'现在就能做', missing:'还缺', item:'样', induction:'电磁炉', gas:'燃气灶 · 稍后', all:'全部菜谱', allSub:'继续往下按菜名或食材搜索', search:'搜索菜名或食材', minutes:'分钟', watts:'功率路线', difficulty:'难度', open:'查看做法与对比', have:'你已经有', need:'还需要', steps:'电磁炉步骤', tip:'电磁炉提示', tipText:'不同机器实际火力有差异。第一次做时以状态判断为主，瓦数用于建立可重复的起点。', submitTitle:'分享你的菜谱或改进建议', submitDesc:'投稿会进入待审核列表。通过后才会转交作者，不会在页面展示作者邮箱。', staticSubmitDesc:'公开预览版暂不接收投稿；投稿后台正在安全接入，作者邮箱不会公开。', name:'怎么称呼你', dish:'菜名', content:'步骤、功率、用量或改进建议', send:'提交审核', comingSoon:'投稿功能正在接入', sending:'正在提交…', success:'已收到，谢谢！审核后会转交作者。', error:'暂时没有提交成功，请稍后重试。', close:'关闭' },
  en: { brand:'SHIZHI', sub:'Induction recipes for students', tested:'Kitchen-tested', guest:'Share a recipe', myIngredients:'What I have', ingredientHint:'Choose ingredients first—we will show what each recipe is missing', add:'Type an ingredient and press Enter', recommend:'Best matches right now', recommendSub:'Matched to your pantry, with kitchen-tested recipes first', can:'Ready to cook', missing:'Missing', item:'', induction:'Induction', gas:'Gas stove · Later', all:'All recipes', allSub:'Scroll down to search by dish or ingredient', search:'Search dishes or ingredients', minutes:'min', watts:'Power map', difficulty:'Difficulty', open:'View method & comparison', have:'You have', need:'You still need', steps:'Induction steps', tip:'Induction note', tipText:'Actual heat varies by hob. On your first try, judge by the food; use wattage as a repeatable starting point.', submitTitle:'Share a recipe or improvement', submitDesc:'Your note enters a review queue. Only useful submissions are forwarded, and the author’s email is never shown.', staticSubmitDesc:'The public preview is not accepting submissions yet. A secure review inbox is being connected, and the author’s email will remain private.', name:'Your name', dish:'Dish name', content:'Steps, wattage, quantities, or suggestions', send:'Submit for review', comingSoon:'Submission inbox coming soon', sending:'Submitting…', success:'Received—thank you! It will be reviewed before forwarding.', error:'Could not submit right now. Please try again later.', close:'Close' },
};

export default function Home() {
  const [lang, setLang] = useState<Lang>('zh'); const t = copy[lang];
  const isStaticPreview = process.env.NEXT_PUBLIC_DEPLOY_TARGET === 'github-pages';
  const [owned, setOwned] = useState(['西红柿','鸡蛋','小葱']); const [ingredient, setIngredient] = useState('');
  const [search, setSearch] = useState(''); const [selected, setSelected] = useState<Recipe | null>(null);
  const [guestOpen, setGuestOpen] = useState(false); const [submitState, setSubmitState] = useState<'idle'|'sending'|'success'|'error'>('idle');
  const [guest, setGuest] = useState({ name:'', dishName:'', content:'' });
  const hasIngredient = useCallback((recipe: Recipe, index: number) => [recipe.ingredients[index], recipe.ingredientEn[index]].some((item) => owned.some((ownedItem)=>ownedItem.toLowerCase()===item.toLowerCase())), [owned]);
  const score = (recipe: Recipe) => recipe.ingredients.filter((_, index) => hasIngredient(recipe, index)).length;
  const sorted = [...recipes].sort((a,b) => score(b)-score(a) || Number(Boolean(b.tested))-Number(Boolean(a.tested)));
  const filtered = recipes.filter((recipe) => !search.trim() || [...recipe.ingredients,...recipe.ingredientEn,recipe.zh,recipe.en].join(' ').toLowerCase().includes(search.toLowerCase()));
  function addIngredient(event: React.KeyboardEvent<HTMLInputElement>) { if (event.key !== 'Enter' || !ingredient.trim()) return; event.preventDefault(); if (!owned.includes(ingredient.trim())) setOwned([...owned, ingredient.trim()]); setIngredient(''); }
  function displayIngredient(item: string) { for (const recipe of recipes) { const zhIndex=recipe.ingredients.findIndex((candidate)=>candidate.toLowerCase()===item.toLowerCase()); const enIndex=recipe.ingredientEn.findIndex((candidate)=>candidate.toLowerCase()===item.toLowerCase()); if (lang==='en'&&zhIndex>=0) return recipe.ingredientEn[zhIndex]; if (lang==='zh'&&enIndex>=0) return recipe.ingredients[enIndex]; } return item; }
  const recipeIngredients = useCallback((recipe: Recipe) => lang === 'zh' ? recipe.ingredients : recipe.ingredientEn, [lang]);
  const missingFor = useCallback((recipe: Recipe) => recipeIngredients(recipe).filter((_, index) => !hasIngredient(recipe, index)), [hasIngredient, recipeIngredients]);
  async function submitGuest(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); if (isStaticPreview) return; setSubmitState('sending'); try { const response = await fetch('/api/submissions', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ ...guest, locale:lang }) }); if (!response.ok) throw new Error(); setSubmitState('success'); setGuest({ name:'', dishName:'', content:'' }); } catch { setSubmitState('error'); } }

  useEffect(() => {
    const context = document.modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController();
    const registration = context.registerTool({ name:'open_recipe', title:'打开菜谱详情', description:'按菜谱 ID 打开菜谱，并显示用户已有与缺少的食材。', inputSchema:{ type:'object', properties:{ recipeId:{ type:'string', enum:recipes.map((recipe)=>recipe.id) } }, required:['recipeId'], additionalProperties:false }, annotations:{ readOnlyHint:true, untrustedContentHint:false }, execute(input:unknown){ const id=(input as {recipeId?:unknown}).recipeId; const recipe=recipes.find((item)=>item.id===id); if(!recipe) throw new Error('Recipe not found'); setSelected(recipe); return { recipeId:recipe.id, title:lang==='zh'?recipe.zh:recipe.en, missing:missingFor(recipe) }; } }, { signal:lifecycle.signal });
    Promise.resolve(registration).catch(()=>lifecycle.abort()); return ()=>lifecycle.abort();
  }, [lang, missingFor]);

  return <main>
    <header className="site-header"><a className="logo" href="#top"><span><Zap /></span><div><strong>{t.brand}</strong><small>{t.sub}</small></div></a><div className="header-actions"><div className="stove-switch"><button className="active"><Zap />{t.induction}</button><button disabled><Flame />{t.gas}</button></div><button className="guest-button" onClick={()=>{setGuestOpen(true);setSubmitState('idle')}}><MessageSquarePlus />{t.guest}</button><div className="language-switch" aria-label="Language"><Globe2 /><button className={lang==='zh'?'active':''} onClick={()=>setLang('zh')}>中文</button><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button></div></div></header>

    <div id="top" className="page-wrap">
      <section className="pantry"><div className="pantry-head"><span className="step">01</span><div><h1>{t.myIngredients}</h1><p>{t.ingredientHint}</p></div></div><div className="ingredient-controls"><div className="chips">{owned.map((item)=><span key={item}>{displayIngredient(item)}<button aria-label={`${t.close} ${displayIngredient(item)}`} onClick={()=>setOwned(owned.filter((ownedItem)=>ownedItem!==item))}><X /></button></span>)}</div><div className="ingredient-input"><Plus /><Input aria-label={t.add} value={ingredient} onChange={(event)=>setIngredient(event.target.value)} onKeyDown={addIngredient} placeholder={t.add} /></div></div></section>

      <section className="recommend"><div className="section-head"><div><span className="step">02</span><h2>{t.recommend}</h2><p>{t.recommendSub}</p></div><a href="#all-recipes">{t.all}<ArrowDown /></a></div><div className="recipe-grid">{sorted.slice(0,4).map((recipe,index)=><RecipeCard key={recipe.id} recipe={recipe} lang={lang} rank={index+1} match={score(recipe)} missing={missingFor(recipe)} onOpen={()=>setSelected(recipe)} />)}</div></section>

      <section className="induction-note"><div className="coil"><span/><span/><span/></div><div><span><Lightbulb />{t.tip}</span><p>{t.tipText}</p></div><strong>500W · 1000W · 1600W</strong></section>

      <section id="all-recipes" className="all-recipes"><div className="section-head"><div><span className="step">03</span><h2>{t.all}</h2><p>{t.allSub}</p></div><div className="search-box"><Search /><Input aria-label={t.search} value={search} onChange={(event)=>setSearch(event.target.value)} placeholder={t.search} /></div></div><div className="recipe-table">{filtered.map((recipe)=><button key={recipe.id} onClick={()=>setSelected(recipe)}><span className="dish-icon"><ChefHat /></span><span><strong>{lang==='zh'?recipe.zh:recipe.en}</strong><small>{recipe.tested&&<em><Check />{t.tested}</em>} {recipeIngredients(recipe).join(' · ')}</small></span><span className="table-meta"><Stars count={recipe.difficulty}/><small>{recipe.minutes} {t.minutes}</small></span><span className="power"><Zap />{recipe.power}</span><ChevronRight /></button>)}</div></section>

      <button className="submission-banner" onClick={()=>{setGuestOpen(true);setSubmitState('idle')}}><MessageSquarePlus /><span><strong>{t.submitTitle}</strong><small>{isStaticPreview?t.staticSubmitDesc:t.submitDesc}</small></span><ChevronRight /></button>
    </div>

    <Sheet open={Boolean(selected)} onOpenChange={(open)=>!open&&setSelected(null)}><SheetContent className="recipe-sheet"><SheetHeader><SheetTitle>{selected&&(lang==='zh'?selected.zh:selected.en)}</SheetTitle><SheetDescription>{selected&&(lang==='zh'?selected.descZh:selected.descEn)}</SheetDescription></SheetHeader>{selected&&<div className="sheet-body"><div className="sheet-stats"><span><Stars count={selected.difficulty}/><small>{t.difficulty}</small></span><span><Clock3/><strong>{selected.minutes} {t.minutes}</strong></span><span><Zap/><strong>{selected.power}</strong></span></div><div className="comparison"><h3>{t.have}</h3><div>{recipeIngredients(selected).filter((item)=>!missingFor(selected).includes(item)).map((item)=><span className="have" key={item}><Check />{item}</span>)}</div><h3>{t.need}</h3><div>{missingFor(selected).length?missingFor(selected).map((item)=><span className="need" key={item}><Plus />{item}</span>):<span className="ready"><Check />{t.can}</span>}</div></div><div className="power-track"><div><span>500W</span><span>1000W</span><span>1600W</span></div><i/></div><div className="steps"><h3><Utensils />{t.steps}</h3>{(lang==='zh'?selected.stepsZh:selected.stepsEn).map((step,index)=><div key={step}><span>{index+1}</span><p>{step}</p></div>)}</div></div>}</SheetContent></Sheet>

    <Dialog open={guestOpen} onOpenChange={setGuestOpen}><DialogContent className="guest-dialog"><DialogHeader><DialogTitle>{t.submitTitle}</DialogTitle><DialogDescription>{isStaticPreview?t.staticSubmitDesc:t.submitDesc}</DialogDescription></DialogHeader>{submitState==='success'?<div className="submit-success"><Check/><p>{t.success}</p><Button onClick={()=>setGuestOpen(false)}>{t.close}</Button></div>:<form onSubmit={submitGuest}><label>{t.name}<Input required maxLength={60} disabled={isStaticPreview} value={guest.name} onChange={(e)=>setGuest({...guest,name:e.target.value})}/></label><label>{t.dish}<Input required maxLength={100} disabled={isStaticPreview} value={guest.dishName} onChange={(e)=>setGuest({...guest,dishName:e.target.value})}/></label><label>{t.content}<textarea required maxLength={2500} disabled={isStaticPreview} value={guest.content} onChange={(e)=>setGuest({...guest,content:e.target.value})}/></label>{submitState==='error'&&<p className="form-error">{t.error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={()=>setGuestOpen(false)}>{t.close}</Button><Button type="submit" disabled={isStaticPreview||submitState==='sending'}>{isStaticPreview?t.comingSoon:submitState==='sending'?t.sending:t.send}<Send/></Button></DialogFooter></form>}</DialogContent></Dialog>
  </main>;
}

function Stars({count}:{count:number}) { return <span className="stars" aria-label={`${count}/3`}>{[1,2,3].map((star)=><Star key={star} className={star<=count?'filled':''}/>)}</span> }
function RecipeCard({recipe,lang,rank,match,missing,onOpen}:{recipe:Recipe;lang:Lang;rank:number;match:number;missing:string[];onOpen:()=>void}) { const t=copy[lang]; return <button className={`recipe-card rank-${rank}`} onClick={onOpen}><div className="card-top"><span className="rank">0{rank}</span>{recipe.tested&&<em><Check />{t.tested}</em>}</div><div className="card-icon"><ChefHat /></div><h3>{lang==='zh'?recipe.zh:recipe.en}</h3><p>{lang==='zh'?recipe.descZh:recipe.descEn}</p><div className="match-bar"><i style={{width:`${Math.round(match/(match+missing.length||1)*100)}%`}}/></div><div className="match-line"><strong className={missing.length?'missing':'ready'}>{missing.length?`${t.missing} ${missing.length} ${t.item}`:t.can}</strong><span>{missing.length?missing.join(' · '):<><Check />100%</>}</span></div><footer><Stars count={recipe.difficulty}/><span><Clock3 />{recipe.minutes} {t.minutes}</span><span><Zap />{recipe.power}</span></footer><div className="open-label">{t.open}<ChevronRight /></div></button> }
